import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Nav } from "@/components/nav";
import { ReactQueryProvider } from "@/providers/react-query.provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <ReactQueryProvider>
          <div className="dark bg-sidebar">
            <div className="relative mx-auto flex max-w-5xl flex-col text-card-foreground md:flex-row">
              <Nav />
              <div className="flex-1 bg-background pb-[60px] md:pb-0 border-accent-foreground border-r border-l">
                {children}
              </div>
            </div>
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
